Input functions
eastgenomics/ConfirmationThresholds pull request #1
Opened 2022-07-14 09:55 UTC by chrispyatt

Ignore unit tests file as not complete yet.

Functions to be reviewed:

1. get_args
2. checkHappyQueryMatch
3. checkMultipleQueryMetrics
4. checkMetrics
5. parseQuery
6. parseHappy
7. getOutputName
8. mergeSamples

Intended flow in main() - any comments welcome.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)

2022-07-14 09:55 UTC, pep8speaks commented
Hello @chrispyatt! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`FPTP.py`](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py):

> [Line 23:1](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L23): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 30:20](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L30): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 31:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L31): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 35:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (226 > 79 characters)
> [Line 38:9](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L38): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 38:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 79 characters)
> [Line 39:5](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L39): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 42:14](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L42): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 53:45](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L53): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 53:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L53): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (151 > 79 characters)
> [Line 62:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 79 characters)
> [Line 65:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 79 characters)
> [Line 72:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L72): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 76:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 77:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 78:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 84:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (150 > 79 characters)
> [Line 91:5](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L91): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 98:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 104:5](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L104): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 110:33](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L110): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 112:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 113:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L113): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 114:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L114): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 115:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L115): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 119:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 79 characters)
> [Line 125:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L125): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 132:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L132): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 79 characters)
> [Line 146:5](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L146): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 154:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L154): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 79 characters)
> [Line 160:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L160): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)
> [Line 162:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L162): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 79 characters)
> [Line 167:45](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L167): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 167:55](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L167): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 168:5](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L168): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 176:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L176): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 183:80](https://github.com/eastgenomics/ConfirmationThresholds/blob/c1 [...]

2022-07-14 12:07 UTC, jethror1 requested changes
pep8 issues I'd look at: E501, E231, W292 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-:-N6wYlhoCHqQRezWDnwI:b-wafsuo)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`FPTP.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZEKh6WI1UNco8BVR:-N6wZEKh6WI1UNco8BVS:ba3qtf5) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L35)):*
> ```Python
>     parser.add_argument(
>         '--query',
>         help='filename of query VCF (containing variants and metric values). Up to two query sample VCFs may be provided, but if a hap.py VCF is provided via the --happy option, only one (matching) query VCF will be accepted.'
> ```

line length, consider formatting like this:

```
    parser.add_argument(
        '--query',
        help=(
            'filename of query VCF (containing variants and metric values). '
            'Up to two query sample VCFs may be provided, but if a hap.py VCF '
            is provided via the --happy option, only one (matching) query VCF '
            'will be accepted.'
        )
    )
```
___
*[`FPTP.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wR_3k-hqnOUL2tr4l:-N6wR_3k-hqnOUL2tr4m:beyfn3n) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L42)):*
does `args == None` ever evaluate to true? when you call `.parse_args()` it returns a NameSpace object which I don't think will be None:

```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> args =  parser.parse_args()  # empty args
>>> if args == None: print ('no args')
... 
>>> 
```

here you can just set `args.query` to have the `required=True` flag if it must be passed: https://docs.python.org/3/library/argparse.html#required.

examples of lots of arguments: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9a83593c1be235d8bf96c3fdd515dbbcb49fba23/resources/home/dnanexus/generate_workbook/generate_workbook.py#L58

also as an aside, the pythonic way to check for truthness is to just use `if` and `if not` instead of checking against `== None`:
```
>>> test1 = None
>>> if not test1: print('its None')
... 
its None
>>> test2 = 'a thing'
>>> if test2: print(f"test 2 exists: {test2}")
... 
test 2 exists: a thing
```
___
*[`FPTP.py` line 53 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wTieg0Po12CcAPH5-:-N6wTieg0Po12CcAPH50:biwy5x0) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L53)):*
> ```Python
>     args.query = args.query.split(',')
>     # exit gracefully if number of input files is incorrect
>     if (len(args.query) == 1 and args.happy == None) or (len(args.query) == 2 and len(args.happy.split(',')) == 1) or (len(args.happy.split(',')) > 1):
> ```

not sure if it's useful here or not but good to be aware of when you want combinations (or not) of arguments: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group
___
*[`FPTP.py` line 61 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVulL2qVqEyeCRfkq:-N6wVulL2qVqEyeCRfkr:b-nrah7h) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L61)):*
> ```Python
> 
> def checkHappyQueryMatch(happy, query):
>     '''
> ```

docstrings defining inputs and outputs (plus raising errors if you're feeling fancy) with types would be good, I like numpys style: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9a83593c1be235d8bf96c3fdd515dbbcb49fba23/resources/home/dnanexus/generate_workbook/utils/filters.py#L33

future you will appreciate knowing what everything is
___
*[`FPTP.py` line 62 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wUezm0w30JVsR-SiM:-N6wUezm0w30JVsR-SiN:b-ohte5v) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L62)):*
> ```Python
> def checkHappyQueryMatch(happy, query):
>     '''
>     Checks that the sample name matches between hap.py VCF and query VCF (as variants will need to be matched between the two to assign TP/FP)
> ```

pep8 line lengths, aim for 72 characters for comments and 79 for code, if you're using VSCode this might be helpful to add rulers to python:

```
    "[python]": {
        "editor.rulers": [
            {
                "column": 72,
                "color": "#054D2B"
            },
            {
                "column": 79,
                "color": "#041C5E"
            }
        ]
    },
```

in preferences -> search 'ruler' -> click edit in settings.json
___
*[`FPTP.py` line 64 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVMEA9t9v05mTeBHJ:-N6wVMEA9t9v05mTeBHK:b-1qc1aa) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L64)):*
> ```Python
>     Checks that the sample name matches between hap.py VCF and query VCF (as variants will need to be matched between the two to assign TP/FP)
>     '''
>     if happy is not None:
> ```

`if happy:`
___
*[`FPTP.py` line 65 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVPAp7uAY_kfUeauS:-N6wVPAp7uAY_kfUeauT:bauyn7l) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L65)):*
> ```Python
>     '''
>     if happy is not None:
>         assert happy.split('.')[0] == query.split('.')[0].split('-')[0], f'hap.py and query vcf sample names do not match ({happy} & {query})'
> ```

line length, strings can go in parentheses for nice formatting and not needing line breaks either:

```
assert happy.split('.')[0] == query.split('.')[0].split('-')[0], (
    f'hap.py and query vcf sample names do not match ({happy} & {query})'
)
```



_Code quote:_
```Python
assert happy.split('.')[0] == query.split('.')[0].split('-')[0], f'hap.py and query vcf sample names do not match ({happy} & {query})'
```
___
*[`FPTP.py` line 91 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZQzeEGt7kOxZ9py1:-N6wZQzeEGt7kOxZ9py2:bwul9g1) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L91)):*
> ```Python
>         else:
>             requestedMetrics = metrics.split(',')
>     except:
> ```

bare exceptions are usually bad as they can catch anything and really hard to debug, as a minimum Id consider catching and displaying the error:

```
except Exception as error:
    print(
        '\nError parsing metrics. Please check formatting.\n'
        f'Error: {error}'
     )
    sys.exit(1)
```

you can then catch specific types of errors if you want to handle them separately and not just exit 
___
*[`FPTP.py` line 96 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6w_fkvBBQdv-CCiaFa:-N6w_fkwCemQq9dr7Mmo:b8bpj6z) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L96)):*
> ```Python
>     try:
>         with open(query) as file:
>             allInfoMetrics = []
> ```

convention for variable and function names is snakecase (lower case with underscores) and classes as camelcase (capitalised):

```
class MyClass():
    '''A class of functions'''

    def my_function():
    '''A function to do a thing'''
         all_info_metrics = []  # some list
```
___
*[`FPTP.py` line 104 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6waRrT3eWKBPxtQagE:-N6waRrT3eWKBPxtQagF:b-1uhl8) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca [...]

2022-07-26 10:53 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 0 of 11 files reviewed, 12 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`FPTP.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZEKh6WI1UNco8BVR:-N7tmU8A8_-phzbxJi-S:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L35)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

line length, consider formatting like this:

```
    parser.add_argument(
        '--query',
        help=(
            'filename of query VCF (containing variants and metric values). '
            'Up to two query sample VCFs may be provided, but if a hap.py VCF '
            is provided via the --happy option, only one (matching) query VCF '
            'will be accepted.'
        )
    )
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wR_3k-hqnOUL2tr4l:-N7tir_VEDkOAY2zbsLM:b-bry1be) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L42)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does `args == None` ever evaluate to true? when you call `.parse_args()` it returns a NameSpace object which I don't think will be None:

```
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> args =  parser.parse_args()  # empty args
>>> if args == None: print ('no args')
... 
>>> 
```

here you can just set `args.query` to have the `required=True` flag if it must be passed: https://docs.python.org/3/library/argparse.html#required.

examples of lots of arguments: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9a83593c1be235d8bf96c3fdd515dbbcb49fba23/resources/home/dnanexus/generate_workbook/generate_workbook.py#L58

also as an aside, the pythonic way to check for truthness is to just use `if` and `if not` instead of checking against `== None`:
```
>>> test1 = None
>>> if not test1: print('its None')
... 
its None
>>> test2 = 'a thing'
>>> if test2: print(f"test 2 exists: {test2}")
... 
test 2 exists: a thing
```
</blockquote></details>

I quite liked the way it printed the help text when exiting this way (making query required just prints the usage bit and a message saying query is required). Is there another way to have it always print the help?
___
*[`FPTP.py` line 53 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wTieg0Po12CcAPH5-:-N7u5w1o7vOaKbZ0zuH7:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L53)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not sure if it's useful here or not but good to be aware of when you want combinations (or not) of arguments: https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group
</blockquote></details>

Done.
___
*[`FPTP.py` line 62 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wUezm0w30JVsR-SiM:-N7u5s5fDCUCNl-niZNE:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L62)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pep8 line lengths, aim for 72 characters for comments and 79 for code, if you're using VSCode this might be helpful to add rulers to python:

```
    "[python]": {
        "editor.rulers": [
            {
                "column": 72,
                "color": "#054D2B"
            },
            {
                "column": 79,
                "color": "#041C5E"
            }
        ]
    },
```

in preferences -> search 'ruler' -> click edit in settings.json
</blockquote></details>

Done.
___
*[`FPTP.py` line 64 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVMEA9t9v05mTeBHJ:-N7u5PXd7mRNjtgCVTA-:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L64)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`if happy:`
</blockquote></details>

Done.
___
*[`FPTP.py` line 65 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVPAp7uAY_kfUeauS:-N7u5Obi4TG27Ug6gyjV:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L65)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

line length, strings can go in parentheses for nice formatting and not needing line breaks either:

```
assert happy.split('.')[0] == query.split('.')[0].split('-')[0], (
    f'hap.py and query vcf sample names do not match ({happy} & {query})'
)
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 91 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZQzeEGt7kOxZ9py1:-N7u5LDw21FO9B5p2LYw:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L91)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

bare exceptions are usually bad as they can catch anything and really hard to debug, as a minimum Id consider catching and displaying the error:

```
except Exception as error:
    print(
        '\nError parsing metrics. Please check formatting.\n'
        f'Error: {error}'
     )
    sys.exit(1)
```

you can then catch specific types of errors if you want to handle them separately and not just exit 
</blockquote></details>

Done.
___
*[`FPTP.py` line 96 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6w_fkvBBQdv-CCiaFa:-N7u5K5tAdN9lHMtLpCR:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L96)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

convention for variable and function names is snakecase (lower case with underscores) and classes as camelcase (capitalised):

```
class MyClass():
    '''A class of functions'''

    def my_function():
    '''A function to do a thing'''
         all_info_metrics = []  # some list
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 104 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6waRrT3eWKBPxtQagE:-N7u5KaICt47D-UH65B-:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L104)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above for bare exception
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 11:06 UTC, chrispyatt commented
have now added some of the processing and output functions - plotting doesn't quite work yet though

2022-07-26 17:04 UTC, jethror1 requested changes
> Reviewed 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`FPTP.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZEKh6WI1UNco8BVR:-N7vQ_OF42zzH3tn7GVF:b-e3jmpu) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L35)):*
inside of parentheses backslaches aren't required and can sometimes cause bad formatting, just add quotes for each line

```
>>> print(
...     'this is a '
...     'multi line string'
... )
this is a multi line string


>>> print(
...     'this is a \
...     multi line string'
... )
this is a       multi line string
```
___
*[`FPTP.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wR_3k-hqnOUL2tr4l:-N7vRSWZ5Xc6dQBGRygL:br9bs5p) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L42)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

I quite liked the way it printed the help text when exiting this way (making query required just prints the usage bit and a message saying query is required). Is there another way to have it always print the help?
</blockquote></details>

not always print, but its common for cmd line tools to require `--help` to print the help, including for argparse:

```
$ python3 generate_workbook/generate_workbook.py --help
usage: Turns an annotated vcf into an xlsx for human viewing [-h] [-v VCFS [VCFS ...]] [--additional_files ADDITIONAL_FILES [ADDITIONAL_FILES ...]]
                                                             [-e EXCLUDE [EXCLUDE ...] | -i INCLUDE [INCLUDE ...]] [-r REORDER [REORDER ...]]
                                                             [-z [RENAME [RENAME ...]]] [-f FILTER] [-t [TYPES [TYPES ...]]] [-k] [--keep_tmp] [-n] [-c]
                                                             [-s SHEETS [SHEETS ...]] [--additional_sheets ADDITIONAL_SHEETS [ADDITIONAL_SHEETS ...]]
                                                             [-o OUTPUT] [--out_dir OUT_DIR] [-m] [--summary SUMMARY]
                                                             [--human_filter HUMAN_FILTER [HUMAN_FILTER ...]] [--acmg] [--job_id JOB_ID]
                                                             [--workflow WORKFLOW WORKFLOW] [--panel PANEL [PANEL ...]]
                                                             [--clinical_indication CLINICAL_INDICATION [CLINICAL_INDICATION ...]] [--sample SAMPLE]
                                                             [--print_columns] [--print_header]

optional arguments:
  -h, --help            show this help message and exit
  -v VCFS [VCFS ...], --vcfs VCFS [VCFS ...]
                        Annotated vcf file(s)
  --additional_files ADDITIONAL_FILES [ADDITIONAL_FILES ...]
                        Additional files to read in and append to additional sheets. Each file should tabulated (comma or tab separated) and will NOT have
                        any of the exclude/rename/filter methods applied. If --sheets is passed this will also rename these sheets.
  -e EXCLUDE [EXCLUDE ...], --exclude EXCLUDE [EXCLUDE ...]
                        Columns from vcf to EXCLUDE from output, by default all INFO and CSQ fields are expanded to their own columns
  -i INCLUDE [INCLUDE ...], --include INCLUDE [INCLUDE ...]
                        Columns in vcf to INCLUDE from output, by default all INFO and CSQ fields are expanded to their own columns
  -r REORDER [REORDER ...], --reorder REORDER [REORDER ...]
                        Set order for columns in output workbook, any not specified will be appended to the end
  -z [RENAME [RENAME ...]], --rename [RENAME [RENAME ...]]
                        Pass pairs of {column_name}={new_column_name} for renaming columns in output excel, should be passed as --rename CHROM=chr POS=pos
                        REF=ref... (use --print_columns to see valid column names)
  -f FILTER, --filter FILTER
                        bcftools filter command to filter variants against
  -t [TYPES [TYPES ...]], --types [TYPES [TYPES ...]]
                        Pass pairs of column=type for modifying types in VCF header,this should be used when the given type in the VCF header is incorrect
                        and needs correcting to allow filtering (i.e. AF fields wrongly set as strings. Types of all fields may be inspected with
                        --print_header.
  -k, --keep            Pass when using --filter to keep filtered variants in a separated "filtered" tab
  --keep_tmp            Pass to keep intermediary split vcf, and filtered vcf if --filter specified
  -n, --add_name        Add sample name from filename as first column
  -c, --add_comment_column
                        Add empty comment column to end of each sheet
  -s SHEETS [SHEETS ...], --sheets SHEETS [SHEETS ...]
                        Names to use for multiple sheets, these MUST be the same number as the number of vcfs passed and in the same order. If not given, if
                        there is 1 vcf passed the sheet will be named "variants", if multiple the name prefix of the vcf will be used
  --additional_sheets ADDITIONAL_SHEETS [ADDITIONAL_SHEETS ...]
                        Names for worksheets of additional files (if given), these MUST be the same number as the number of files passed to
                        --additional_files. If not given, file prefixes will be used.
  -o OUTPUT, --output OUTPUT
                        output name prefix for file, if more than 1 vcf passed a name must be specified. If only 1 vcf passed and no output name, the vcf
                        filename prefix will be used
  --out_dir OUT_DIR     path to output directory
  -m, --merge           Merge multiple vcfs into one combined sheet of variants to display
  --summary SUMMARY     summary sheet to include, must be one of: dias
  --human_filter HUMAN_FILTER [HUMAN_FILTER ...]
                        String to add to summary sheet with humanly readable form of the given filter string. No checking is done of this matching the actual
                        filter(s) used.
  --acmg                add extra ACMG reporting template sheet
  --job_id JOB_ID       Job ID of eggd_generate_workbook to add to Dias summary
  --workflow WORKFLOW WORKFLOW
                        Name and ID of workflow to display in summary
  --panel PANEL [PANEL ...]
                        panel name to display in summary
  --clinical_indication CLINICAL_INDICATION [CLINICAL_INDICATION ...]
                        clinical indication to write into summary sheet
  --sample SAMPLE       name of sample to display in summary report
  --print_columns       Print total columns of all vcfs that will be output to the workbook. Useful to identify what will be in the output to include/exclude
  --print_header        Print header from first given VCF. Useful for identifying available INFO/FORMAT/CSQ fields and their types.n.b. CSQ fields are
                        prefixed with "CSQ_", this is stripped before writing to the Excel file.
```

it's fine if you want to keep it like that, but the first `if not args` is redundant


<!-- Sent from Reviewable.io -->

2022-08-01 15:40 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 8 of 11 files reviewed, 14 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`FPTP.py` line 85 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_Yd92JM71Mciuoez:-N8O_Yd92JM71Mciuof-:bq41a65) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L85)):*
> ```Python
>         or (len(args.query) == 2 and len(args.happy.split(',')) == 1)
>         or (len(args.happy.split(',')) > 1)
>     ):
> ```

I'd print the issue here as it would be confusing if you tried to run it and just got the help
___
*[`FPTP.py` line 99 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_iPFA9TQcupAKL6d:-N8O_iPFA9TQcupAKL6e:b7lzkrj) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L99)):*
> ```Python
>     '''
>     try:
>         # is declaring as global necessary if declared at top of script?
> ```

nope since when its in the global scope (i.e outside of the functions) it will already be available inside functions
___
*[`FPTP.py` line 102 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_rg37W6HVMjmA72n:-N8O_rg37W6HVMjmA72o:b-1vdh2m) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L102)):*
> ```Python
>         global SAMPLE1_NAME
>         global SAMPLE2_NAME
>         SAMPLE1_NAME = re.split('[.-]', sample1)[0]
> ```

be careful reassinging to the global variable, can be likely to introduce bugs if done elsewhere
___
*[`FPTP.py` line 160 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OaJyA7l4Rigxlsmsi:-N8OaJyA7l4Rigxlsmsj:bltufwp) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L160)):*
> ```Python
>         sys.exit(1)
>     try:
>         with gzip.open(query, 'rt') as file:
> ```

do you intentionally not handle non-compressed files?
___
*[`FPTP.py` line 165 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8ObTiT3MTNLKpevctS:-N8ObTiT3MTNLKpevctT:b-fm6kyb) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L165)):*
> ```Python
>             # parse out metric names - separate info and format metrics in case of identical names (usually DP)
>             for line in file:
>                 # grab only metrics where the type is float or integer (as others cannot be plotted) and also where the number of values is constrained to 1. The latter constraint will be modified to accept lists of values in later versions of this tool.
> ```

line length
___
*[`FPTP.py` line 166 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OaVIXBedGtPgEyUzC:-N8OaVIXBedGtPgEyUzD:b-et8mtm) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L166)):*
> ```Python
>             for line in file:
>                 # grab only metrics where the type is float or integer (as others cannot be plotted) and also where the number of values is constrained to 1. The latter constraint will be modified to accept lists of values in later versions of this tool.
>                 if line.startswith('##INFO') and ('Integer' in line.split(',')[2] or 'Float' in line.split(',')[2]) and line.split(',')[1] == 'Number=1':
> ```

this isn't always 100% reliable as float values sometimes get (wrongly) assigned as strings in the header:
```
$ zgrep '##INFO' ~/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests/test_data/NA12878_unittest.split.vcf | grep String
##INFO=<ID=ClinVar,Number=.,Type=String,Description="/opt/vep/.vep/clinvar_20211113_withChr.vcf.gz (exact)">
##INFO=<ID=ClinVar_CLNSIG,Number=.,Type=String,Description="CLNSIG field from /opt/vep/.vep/clinvar_20211113_withChr.vcf.gz">
##INFO=<ID=ClinVar_CLNREVSTAT,Number=.,Type=String,Description="CLNREVSTAT field from /opt/vep/.vep/clinvar_20211113_withChr.vcf.gz">
##INFO=<ID=ClinVar_CLNDN,Number=.,Type=String,Description="CLNDN field from /opt/vep/.vep/clinvar_20211113_withChr.vcf.gz">
##INFO=<ID=COSMIC,Number=.,Type=String,Description="/opt/vep/.vep/CosmicCodingMuts_v94_grch37.normal.vcf.gz (exact)">
##INFO=<ID=COSMIC_ID,Number=.,Type=String,Description="ID field from /opt/vep/.vep/CosmicCodingMuts_v94_grch37.normal.vcf.gz">
##INFO=<ID=gnomADg,Number=.,Type=String,Description="/opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz (exact)">
##INFO=<ID=gnomADg_AF,Number=.,Type=String,Description="AF field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_AFR,Number=.,Type=String,Description="AF_AFR field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_AMR,Number=.,Type=String,Description="AF_AMR field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_ASJ,Number=.,Type=String,Description="AF_ASJ field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_EAS,Number=.,Type=String,Description="AF_EAS field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_FIN,Number=.,Type=String,Description="AF_FIN field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_NFE,Number=.,Type=String,Description="AF_NFE field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_OTH,Number=.,Type=String,Description="AF_OTH field from /opt/vep/.vep/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz">
##INFO=<ID=CSQ_SYMBOL,Number=.,Type=String,Description="The CSQ_SYMBOL field from INFO/CSQ">
##INFO=<ID=CSQ_VARIANT_CLASS,Number=.,Type=String,Description="The CSQ_VARIANT_CLASS field from INFO/CSQ">
##INFO=<ID=CSQ_Consequence,Number=.,Type=String,Description="The CSQ_Consequence field from INFO/CSQ">
##INFO=<ID=CSQ_EXON,Number=.,Type=String,Description="The CSQ_EXON field from INFO/CSQ">
##INFO=<ID=CSQ_HGVSc,Number=.,Type=String,Description="The CSQ_HGVSc field from INFO/CSQ">
##INFO=<ID=CSQ_HGVSp,Number=.,Type=String,Description="The CSQ_HGVSp field from INFO/CSQ">
##INFO=<ID=CSQ_CADD_PHRED,Number=.,Type=String,Description="The CSQ_CADD_PHRED field from INFO/CSQ">
##INFO=<ID=CSQ_Existing_variation,Number=.,Type=String,Description="The CSQ_Existing_variation field from INFO/CSQ">
##INFO=<ID=CSQ_ClinVar,Number=.,Type=String,Description="The CSQ_ClinVar field from INFO/CSQ">
##INFO=<ID=CSQ_ClinVar_CLNDN,Number=.,Type=String,Description="The CSQ_ClinVar_CLNDN field from INFO/CSQ">
##INFO=<ID=CSQ_ClinVar_CLNSIG,Number=.,Type=String,Description="The CSQ_ClinVar_CLNSIG field from INFO/CSQ">
##INFO=<ID=CSQ_COSMIC,Number=.,Type=String,Description="The CSQ_COSMIC field from INFO/CSQ">
##INFO=<ID=CSQ_Feature,Number=.,Type=String,Description="The CSQ_Feature field from INFO/CSQ">
```

If you don't want to handle it its fine, just add it as a constraint in the readme 
___
*[`FPTP.py` line 166 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8Oc4GJBkzMyyg9p6lp:-N8Oc4GJBkzMyyg9p6lq:bf2rguv) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L166)):*
> ```Python
>             for line in file:
>                 # grab only metrics where the type is float or integer (as others cannot be plotted) and also where the number of values is constrained to 1. The latter constraint will be modified to accept lists of values in later versions of this tool.
>                 if line.startswith('##INFO') and ('Integer' in line.split(',')[2] or 'Float' in line.split(',')[2]) and line.split(',')[1] == 'Number=1':
> ```

also consider writing long logical statements something like th [...]

2022-08-08 23:19 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 8 of 11 files reviewed, 14 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`FPTP.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wZEKh6WI1UNco8BVR:-N8zgDDo2X16wuxGuZNR:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L35)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

inside of parentheses backslaches aren't required and can sometimes cause bad formatting, just add quotes for each line

```
>>> print(
...     'this is a '
...     'multi line string'
... )
this is a multi line string


>>> print(
...     'this is a \
...     multi line string'
... )
this is a       multi line string
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wR_3k-hqnOUL2tr4l:-N8zgMRs1G5L4iPOvr3t:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L42)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not always print, but its common for cmd line tools to require `--help` to print the help, including for argparse:

```
$ python3 generate_workbook/generate_workbook.py --help
usage: Turns an annotated vcf into an xlsx for human viewing [-h] [-v VCFS [VCFS ...]] [--additional_files ADDITIONAL_FILES [ADDITIONAL_FILES ...]]
                                                             [-e EXCLUDE [EXCLUDE ...] | -i INCLUDE [INCLUDE ...]] [-r REORDER [REORDER ...]]
                                                             [-z [RENAME [RENAME ...]]] [-f FILTER] [-t [TYPES [TYPES ...]]] [-k] [--keep_tmp] [-n] [-c]
                                                             [-s SHEETS [SHEETS ...]] [--additional_sheets ADDITIONAL_SHEETS [ADDITIONAL_SHEETS ...]]
                                                             [-o OUTPUT] [--out_dir OUT_DIR] [-m] [--summary SUMMARY]
                                                             [--human_filter HUMAN_FILTER [HUMAN_FILTER ...]] [--acmg] [--job_id JOB_ID]
                                                             [--workflow WORKFLOW WORKFLOW] [--panel PANEL [PANEL ...]]
                                                             [--clinical_indication CLINICAL_INDICATION [CLINICAL_INDICATION ...]] [--sample SAMPLE]
                                                             [--print_columns] [--print_header]

optional arguments:
  -h, --help            show this help message and exit
  -v VCFS [VCFS ...], --vcfs VCFS [VCFS ...]
                        Annotated vcf file(s)
  --additional_files ADDITIONAL_FILES [ADDITIONAL_FILES ...]
                        Additional files to read in and append to additional sheets. Each file should tabulated (comma or tab separated) and will NOT have
                        any of the exclude/rename/filter methods applied. If --sheets is passed this will also rename these sheets.
  -e EXCLUDE [EXCLUDE ...], --exclude EXCLUDE [EXCLUDE ...]
                        Columns from vcf to EXCLUDE from output, by default all INFO and CSQ fields are expanded to their own columns
  -i INCLUDE [INCLUDE ...], --include INCLUDE [INCLUDE ...]
                        Columns in vcf to INCLUDE from output, by default all INFO and CSQ fields are expanded to their own columns
  -r REORDER [REORDER ...], --reorder REORDER [REORDER ...]
                        Set order for columns in output workbook, any not specified will be appended to the end
  -z [RENAME [RENAME ...]], --rename [RENAME [RENAME ...]]
                        Pass pairs of {column_name}={new_column_name} for renaming columns in output excel, should be passed as --rename CHROM=chr POS=pos
                        REF=ref... (use --print_columns to see valid column names)
  -f FILTER, --filter FILTER
                        bcftools filter command to filter variants against
  -t [TYPES [TYPES ...]], --types [TYPES [TYPES ...]]
                        Pass pairs of column=type for modifying types in VCF header,this should be used when the given type in the VCF header is incorrect
                        and needs correcting to allow filtering (i.e. AF fields wrongly set as strings. Types of all fields may be inspected with
                        --print_header.
  -k, --keep            Pass when using --filter to keep filtered variants in a separated "filtered" tab
  --keep_tmp            Pass to keep intermediary split vcf, and filtered vcf if --filter specified
  -n, --add_name        Add sample name from filename as first column
  -c, --add_comment_column
                        Add empty comment column to end of each sheet
  -s SHEETS [SHEETS ...], --sheets SHEETS [SHEETS ...]
                        Names to use for multiple sheets, these MUST be the same number as the number of vcfs passed and in the same order. If not given, if
                        there is 1 vcf passed the sheet will be named "variants", if multiple the name prefix of the vcf will be used
  --additional_sheets ADDITIONAL_SHEETS [ADDITIONAL_SHEETS ...]
                        Names for worksheets of additional files (if given), these MUST be the same number as the number of files passed to
                        --additional_files. If not given, file prefixes will be used.
  -o OUTPUT, --output OUTPUT
                        output name prefix for file, if more than 1 vcf passed a name must be specified. If only 1 vcf passed and no output name, the vcf
                        filename prefix will be used
  --out_dir OUT_DIR     path to output directory
  -m, --merge           Merge multiple vcfs into one combined sheet of variants to display
  --summary SUMMARY     summary sheet to include, must be one of: dias
  --human_filter HUMAN_FILTER [HUMAN_FILTER ...]
                        String to add to summary sheet with humanly readable form of the given filter string. No checking is done of this matching the actual
                        filter(s) used.
  --acmg                add extra ACMG reporting template sheet
  --job_id JOB_ID       Job ID of eggd_generate_workbook to add to Dias summary
  --workflow WORKFLOW WORKFLOW
                        Name and ID of workflow to display in summary
  --panel PANEL [PANEL ...]
                        panel name to display in summary
  --clinical_indication CLINICAL_INDICATION [CLINICAL_INDICATION ...]
                        clinical indication to write into summary sheet
  --sample SAMPLE       name of sample to display in summary report
  --print_columns       Print total columns of all vcfs that will be output to the workbook. Useful to identify what will be in the output to include/exclude
  --print_header        Print header from first given VCF. Useful for identifying available INFO/FORMAT/CSQ fields and their types.n.b. CSQ fields are
                        prefixed with "CSQ_", this is stripped before writing to the Excel file.
```

it's fine if you want to keep it like that, but the first `if not args` is redundant
</blockquote></details>

Done.
___
*[`FPTP.py` line 61 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wVulL2qVqEyeCRfkq:-N8zhU8IAAM08LfPKhPC:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L61)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

docstrings defining inputs and outputs (plus raising errors if you're feeling fancy) with types would be good, I like numpys style: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9a83593c1be235d8bf96c3fdd515dbbcb49fba23/resources/home/dnanexus/generate_workbook/utils/filters.py#L33

future you will appreciate knowing what everyt [...]

2022-08-09 13:38 UTC, jethror1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 8 of 11 files reviewed, 11 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`FPTP.py` line 99 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_iPFA9TQcupAKL6d:-N91muIk7QRZ1QHCvNzg:b-fuuu3e) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L99)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

Done.
</blockquote></details>

do you still need this function?
___
*[`FPTP.py` line 160 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OaJyA7l4Rigxlsmsi:-N91n_87D56xZH6MIRoZ:b-f8yic7) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L160)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

no I just figured the files this will run on will naturally be gzipped
</blockquote></details>

nope and we have lots of examples where outputs aren't, either check if it doesn't end in `.gz` and raise something like a `RunTimeError` or handle something like here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/288cdacba21ff22e5496fe9aeff0afe0ad54abba/resources/home/dnanexus/generate_workbook/utils/vcf.py#L378
___
*[`FPTP.py` line 165 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8ObTiT3MTNLKpevctS:-N91oAm0CZAOLMhVE3oB:bw9l74j) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L165)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

Done.
</blockquote></details>

have you?
___
*[`FPTP.py` line 219 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OegvP9JqeWimfPHoI:-N91owJOCHs4F5rmZ2I6:b6j7dqq) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L219)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

will change this on other branch as I changed the logic somewhere. I had skipped pyvcf as I thought it couldn't handle the extra fields in the hap.py vcf but Matt explained how to do it.
</blockquote></details>

that's fair, will check on the other later


<!-- Sent from Reviewable.io -->

2022-08-09 23:21 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 8 of 11 files reviewed, 11 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 156 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wWWf36U0qShQdLebK:-N93snuR78KCCwtlSTGT:b-fmjqeh) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L156)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'd recommend using pandas here to read in the vcf since its tabulated data and thats what pandas is made for, example function I use: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9a83593c1be235d8bf96c3fdd515dbbcb49fba23/resources/home/dnanexus/generate_workbook/utils/vcf.py#L260

if you don't need the header you can ignore everything else there except for this:
```
 vcf_df = pd.read_csv(
            vcf, sep='\t', comment='#', names=columns, compression='infer'
        )
```

`comment='#'` skips header lines

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

to then get field you can use `.apply()` etc on the info/format columns to select out what you need, let me know if you need help, might be worth using a jupyter notebook to have a play around with it
</blockquote></details>

I used pyvcf again (other branch). Seems to work
___
*[`FPTP.py` line 189 at r1](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N6wXWTlE0ooQmdN4xl5:-N93u-xx4OJWGTU0_FS_:bkb2wgg) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/c16cc895b615b28201fceca3ecdc94e92e3b016c/FPTP.py#L189)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

where you're splitting things to get names the Path module could be useful: https://docs.python.org/3/library/pathlib.html

```
>>> import pathlib
>>> pathlib.PurePath('NA12878_unittest.split.vcf')
PurePosixPath('NA12878_unittest.split.vcf')
>>> pathlib.PurePath('NA12878_unittest.split.vcf').name
'NA12878_unittest.split.vcf'
>>> pathlib.PurePath('NA12878_unittest.split.vcf').suffix
'.vcf'
>>> pathlib.PurePath('NA12878_unittest.split.vcf').suffixes
['.split', '.vcf']
>>> pathlib.PurePath('NA12878_unittest.split.vcf').stem
'NA12878_unittest.split'
```
</blockquote></details>

I'm currently splitting down to get the 'NA12878' bit so think I need to split the string anyway but I might add the path bit in case users give full paths rather than files in cwd (maybe moot once in dx app but will do anyway)
___
*[`FPTP.py` line 99 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_iPFA9TQcupAKL6d:-N92P7LP1r49QlCZRtrK:bp221qi) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L99)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you still need this function?
</blockquote></details>

it's only used in the merge_samples function later on - but that's not in play for v1 as I'm concentrating on getting True Pos/False Pos done (then later version will add comparison between two samples). There's probably a better way to store/get the sample names.
___
*[`FPTP.py` line 160 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OaJyA7l4Rigxlsmsi:-N92TDTeC7_bvuaawVdg:bhwengz) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L160)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

nope and we have lots of examples where outputs aren't, either check if it doesn't end in `.gz` and raise something like a `RunTimeError` or handle something like here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/288cdacba21ff22e5496fe9aeff0afe0ad54abba/resources/home/dnanexus/generate_workbook/utils/vcf.py#L378
</blockquote></details>

I'll add a little handler section to raise specific error
___
*[`FPTP.py` line 165 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8ObTiT3MTNLKpevctS:-N92T4siAaR3QorAleu3:b-kb446u) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L165)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

have you?
</blockquote></details>

Just realised I've been ticking these off on the wrong branch    -_-
___
*[`FPTP.py` line 219 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OegvP9JqeWimfPHoI:-N93sY6R10KT8-SK6UQV:b1r5qdd) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L219)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

that's fair, will check on the other later
</blockquote></details>

I'll PR that extra branch into this one I think (and then the whole lot can go into release?)


<!-- Sent from Reviewable.io -->

2022-08-17 15:14 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 1 of 14 files reviewed, 11 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 160 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8OaJyA7l4Rigxlsmsi:-N9gMFJe2MLW3LiA0uwl:brc992s) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L160)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

I'll add a little handler section to raise specific error
</blockquote></details>

this was negated by the move to pyvcf


<!-- Sent from Reviewable.io -->

2022-08-18 07:06 UTC, jethror1 requested changes
> Reviewed 9 of 12 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`FPTP.py` line 99 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_iPFA9TQcupAKL6d:-N9jjhjxDu7TU3isjkj1:byku8xx) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L99)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

it's only used in the merge_samples function later on - but that's not in play for v1 as I'm concentrating on getting True Pos/False Pos done (then later version will add comparison between two samples). There's probably a better way to store/get the sample names.
</blockquote></details>

a good way to handle this is through using classes and attributes, as you could intialise the class with these then access them through `self`, can be a thing for the next version
___
*[`FPTP_tests.py` line 12 at r10](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9jkTogCPS-UNpSPje7:-N9jkTogCPS-UNpSPje8:b-7jukpa) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/9efee9fbf21a66058f2922374ef9884a1f8a3333/FPTP_tests.py#L12)):*
> ```Python
> 
> 
>     def test_checkHappyQueryMatch(self):
> ```

could you add docstrings to each test to be explicit about what it is checking
___
*[`FPTP_tests.py` line 18 at r10](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9jkeyZ0S2JKeiHrncK:-N9jkeyZ0S2JKeiHrncL:b-yodlf1) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/9efee9fbf21a66058f2922374ef9884a1f8a3333/FPTP_tests.py#L18)):*
> ```Python
> 
>     def test_checkMultipleQueryMetrics(self):
>         self.assertEqual(checkMultipleQueryMetrics(["NA12878-query.vcf", "sample1-query.vcf"],['AD','DP','GQ','AC','AF','AN','BaseQRankSum']),[['AD','DP','GQ']['AC','AF','AN','BaseQRankSum']])
> ```

line lnngths in test still want to be pep8 happy, something like this:

```
 def test_checkMultipleQueryMetrics(self):
        self.assertEqual(checkMultipleQueryMetrics([
            "NA12878-query.vcf", "sample1-query.vcf"
        ], ['AD','DP','GQ','AC','AF','AN','BaseQRankSum'
        ]), [['AD','DP','GQ']['AC','AF','AN','BaseQRankSum']])

```



_Code quote:_
```Python
    def test_checkMultipleQueryMetrics(self):
        self.assertEqual(checkMultipleQueryMetrics(["NA12878-query.vcf", "sample1-query.vcf"],['AD','DP','GQ','AC','AF','AN','BaseQRankSum']),[['AD','DP','GQ']['AC','AF','AN','BaseQRankSum']])
```


<!-- Sent from Reviewable.io -->

2022-08-18 10:43 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 99 at r4](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N8O_iPFA9TQcupAKL6d:-N9kMOKx2vgG8uY_-4gN:b89f616) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/ba009c5fd6fac0ee5349d6e217f927027788aed7/FPTP.py#L99)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

a good way to handle this is through using classes and attributes, as you could intialise the class with these then access them through `self`, can be a thing for the next version
</blockquote></details>

I'll add this as a TODO / something on the board
___
*[`FPTP_tests.py` line 12 at r10](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9jkTogCPS-UNpSPje7:-N9kY1XK3L7H0WLKhnta:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/9efee9fbf21a66058f2922374ef9884a1f8a3333/FPTP_tests.py#L12)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could you add docstrings to each test to be explicit about what it is checking
</blockquote></details>

Done.
___
*[`FPTP_tests.py` line 18 at r10](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9jkeyZ0S2JKeiHrncK:-N9kY2_OEn0mrvrrK8mx:b-ft4f3v) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/9efee9fbf21a66058f2922374ef9884a1f8a3333/FPTP_tests.py#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

line lnngths in test still want to be pep8 happy, something like this:

```
 def test_checkMultipleQueryMetrics(self):
        self.assertEqual(checkMultipleQueryMetrics([
            "NA12878-query.vcf", "sample1-query.vcf"
        ], ['AD','DP','GQ','AC','AF','AN','BaseQRankSum'
        ]), [['AD','DP','GQ']['AC','AF','AN','BaseQRankSum']])

```
</blockquote></details>

Done. (linter has died so might have missed a couple)


<!-- Sent from Reviewable.io -->

2022-08-18 11:59 UTC, jethror1 requested changes
> Reviewed 1 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @chrispyatt, @jethror1, and @mattgarner)

___
*[`FPTP.py` line 16 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kntWh1MJOKOryt5i8:-N9kntWh1MJOKOryt5i9:bkgz3fe) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP.py#L16)):*
> ```Python
> import pandas as pd
> import scipy.stats as st
> import plotly.io as pio
> ```

pep8 ordering convention for imports is generally be alphanumeric and split into 3 groups, something like:

```
standard libraries (i.e. argparse, sys)

3rd party libraries (i.e. pandas, scipy)

local imports (i.e. from another local script )
```

its not essential but when you get to having a lot of imports it makes it a lot clearer: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/excel.py



_Code quote:_
```Python
import re
import sys
import math
import numpy as np
import pandas as pd
import scipy.stats as st
import plotly.io as pio
import plotly.express as px
from plotly.subplots import make_subplots
import vcf
```
___
*[`FPTP_tests.py` line 7 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9km0R8DBMq7Rjz4cR0:-N9km0R8DBMq7Rjz4cR1:b-3j1eg3) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L7)):*
this would be better storing in a json file and reading in to keep your test data separate.

If you were to have it in a file something like this would work to load into a dict:
```
$ cat test.json 
{
        "thing": "some_value",
        "another_thing": "another_value"
}


>>> import json
>>> with open('test.json', 'r') as fh:
...     test_dict = json.load(fh)
... 

>>> test_dict
{'thing': 'some_value', 'another_thing': 'another_value'}

```
___
*[`FPTP_tests.py` line 270 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kmNNuA92cPI88cIuF:-N9kmNNuA92cPI88cIuG:b-mwq3w3) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L270)):*
> ```Python
> 	}
> test_arrays = [['TP', 21.0, 79.0, 43.0, 63.0, 64.0, 66.0, 75.0], ['FP']]
> test_figure = ('Figure({\n\
> ```

same as above, could this be a in test file and read in to keep the data separate from the tests?

a directory structure like this with a dir for test data might help as you add more things: https://github.com/eastgenomics/eggd_generate_variant_workbook/tree/master/resources/home/dnanexus/generate_workbook/tests
___
*[`FPTP_tests.py` line 656 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kmnfk6EnVv0TEDEfu:-N9kmnfk6EnVv0TEDEfv:bf61y46) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L656)):*
> ```Python
> 
>     def test_make_report(self):
>         # how to test that it writes to file without writing to file?
> ```

you can gave tests that will write to a file, test it is correct then delete it with something like `os.remove(file)`. if you do this lots it can be useful to have a `clean_up()` method


<!-- Sent from Reviewable.io -->

2022-08-22 12:02 UTC, chrispyatt reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 16 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kntWh1MJOKOryt5i8:-N9kqheSECPxj_-TlhxH:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP.py#L16)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pep8 ordering convention for imports is generally be alphanumeric and split into 3 groups, something like:

```
standard libraries (i.e. argparse, sys)

3rd party libraries (i.e. pandas, scipy)

local imports (i.e. from another local script )
```

its not essential but when you get to having a lot of imports it makes it a lot clearer: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/master/resources/home/dnanexus/generate_workbook/utils/excel.py
</blockquote></details>

Done.
___
*[`FPTP_tests.py` line 7 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9km0R8DBMq7Rjz4cR0:-N9lq-uXC4uJd37iSbAy:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L7)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this would be better storing in a json file and reading in to keep your test data separate.

If you were to have it in a file something like this would work to load into a dict:
```
$ cat test.json 
{
        "thing": "some_value",
        "another_thing": "another_value"
}


>>> import json
>>> with open('test.json', 'r') as fh:
...     test_dict = json.load(fh)
... 

>>> test_dict
{'thing': 'some_value', 'another_thing': 'another_value'}

```
</blockquote></details>

Done.
___
*[`FPTP_tests.py` line 270 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kmNNuA92cPI88cIuF:-N9lq1P78k6ErceiXcV1:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L270)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above, could this be a in test file and read in to keep the data separate from the tests?

a directory structure like this with a dir for test data might help as you add more things: https://github.com/eastgenomics/eggd_generate_variant_workbook/tree/master/resources/home/dnanexus/generate_workbook/tests
</blockquote></details>

Done.
___
*[`FPTP_tests.py` line 656 at r11](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-N9kmnfk6EnVv0TEDEfu:-NA4LJQ819sXqUtNc4Pi:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/e0bff232261ed0b8e472fce538989d3fd861e6a8/FPTP_tests.py#L656)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you can gave tests that will write to a file, test it is correct then delete it with something like `os.remove(file)`. if you do this lots it can be useful to have a `clean_up()` method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 12:04 UTC, jethror1 reviewed
> Reviewed 1 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2022-08-22 12:05 UTC, jethror1 reviewed
> Reviewed 1 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2022-08-22 12:05 UTC, jethror1 reviewed
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @jethror1 and @mattgarner)



<!-- Sent from Reviewable.io -->

2022-08-22 12:05 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/1#-:-NA4RLLkBlyXegOtiwyR:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @jethror1 and @mattgarner)



<!-- Sent from Reviewable.io -->

2022-08-22 13:44 UTC, merged